members/crm/urls.py
from django.urls import path

from .views import OrganizationIndex, OrganizationDetailView, OrganizationEdit, \
    ReportedStatisticDetailView, ReportedStatisticEditView, ReportedStatisticAddView, \
    AddressEditView

from vanilla import TemplateView

app_name = 'crm'
urlpatterns = [
    path('member/view/<int:pk>/', OrganizationDetailView.as_view(), name='organization-view'),
    path('member/edit/<int:pk>/', OrganizationEdit.as_view(), name='organization-edit'),
    path('member/address/edit/<int:pk>/', AddressEditView.as_view(), name='address-edit'),
    path('member/statistics/view/<int:pk>/', ReportedStatisticDetailView.as_view(),
        name='reported-statistics-view'),
    path('member/statistics/edit/<int:pk>/', ReportedStatisticEditView.as_view(), name='reported-statistics-edit'),
    path('member/statistics/add/<int:pk>/', ReportedStatisticAddView.as_view(), name='reported-statistics-add'),
    path('', OrganizationIndex.as_view(), name='index'),
]

members/elections/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import (
    CandidateAddView,
    CandidateEditView,
    CandidateView,
    ElectionListView,
    VoteView,
    VoteAddFormView,
    VoteResults,
)
from .api import ElectionCandidatesListAPIView

app_name = "elections"
urlpatterns = [
    path("candidate/nominate/", CandidateAddView.as_view(), name="candidate-add"),
    path(
        "candidate/edit/<str:key>/",
        CandidateEditView.as_view(lookup_field="edit_link_key", lookup_url_kwarg="key"),
        name="candidate-edit",
    ),
    path(
        "candidate/view/<str:key>/",
        CandidateView.as_view(lookup_field="view_link_key", lookup_url_kwarg="key"),
        name="candidate-view",
    ),
    path(
        "candidate/list/<str:key>/",
        ElectionListView.as_view(
            lookup_field="view_nominations_key", lookup_url_kwarg="key"
        ),
        name="candidate-list",
    ),
    path(
        "api/candidate/list/<str:key>/",
        ElectionCandidatesListAPIView.as_view(),
        name="api-candidate-list",
    ),
    path("vote/add/<int:pk>/", VoteAddFormView.as_view(), name="vote-add"),
    path("vote/<int:pk>/", VoteView.as_view(), name="vote-view"),
    path("vote/results/", VoteResults.as_view(), name="vote-results"),
]

members/members/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static

from django.contrib import admin
from django.views.static import serve
from crm.views import IndexView, LoginKeyCheckView

admin.autodiscover()

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("api/v1/", include("crm.urls_api")),
    path("crm/", include("crm.urls")),
    path("staff/", include("crm.urls_staff")),
    path("application/", include("crm.urls_application")),
    path(
        "login/<str:key>/",
        LoginKeyCheckView.as_view(),
        name="login-key-check",
    ),
    path("conferences/", include("conferences.urls")),
    path("elections/", include("elections.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("", IndexView.as_view(), name="crm_index"),
]

if settings.DEBUG:
    urlpatterns += [
        path(
            "media/logos/<path:path>",
            serve,
            {"document_root": settings.MEDIA_ROOT + '/logos/'},
        ),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/crm/models.py
# -*- coding: utf-8 -*-
import os
import uuid
import subprocess
import datetime
import time
import random
import arrow
import sys

from django.db import models, IntegrityError
from django.db.models.signals import post_save
from django.utils.text import slugify
from django.urls import reverse
from django.core.mail import send_mail, EmailMessage
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.conf import settings
from django.dispatch import receiver

from quickbooks import Oauth2SessionManager
from quickbooks import QuickBooks
from quickbooks.exceptions import QuickbooksException
from quickbooks.helpers import qb_date_format
from quickbooks.objects.base import PhoneNumber, EmailAddress
from quickbooks.objects.base import Address as QuickBooksAddress
from quickbooks.objects.customer import Customer
from quickbooks.objects.detailline import SalesItemLine, SalesItemLineDetail
from quickbooks.objects.invoice import Invoice as QuickBooksInvoice
from quickbooks.objects.item import Item
from quickbooks.objects.term import Term

from geopy import geocoders
from geopy.exc import GeocoderTimedOut

from .utils import print_pdf

here = lambda x: os.path.join(os.path.dirname(os.path.abspath(__file__)), x)


class Continent(models.Model):
    name = models.CharField(max_length=192, unique=True, blank=True)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=192, unique=True, blank=True)
    iso_code = models.CharField(max_length=6, unique=True, blank=True)
    developing = models.BooleanField()
    continent = models.ForeignKey(Continent, models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


ORGANIZATION_MEMBERSHIP_TYPE_CHOICES = (
    (5, "Institutional Members"),
    (10, "Institutional Members - MRC"),
    (11, "Institutional Members - DC"),
    (12, "Institutional Members - DC - MRC"),
    (9, "Associate Institutional Members"),
    (17, "Associate Institutional Members - DC"),
    (6, "Organizational Members"),
    (13, "Organizational Members - DC"),
    (18, "Organizational Members - MRC"),
    (7, "Associate Consortium Members"),
    (14, "Associate Consortium Members - DC"),
    (8, "Corporate Members - Basic"),
    (15, "Corporate Members - Premium"),
    (16, "Corporate Members - Sustaining"),
)

ORGANIZATION_TYPE_CHOICES = (
    ("university", "Higher Education Institution"),
    ("npo", "Non-Profit Organization"),
    ("ngo", "Non-Governmental Organization"),
    ("regionalconsortium", "Regional Consortium"),
    ("software", "Software Development"),
    ("commercial", "Commercial Entity"),
)

INSTITUTION_TYPE_CHOICES = (
    ("secondary-ed", "Primary and secondary (K-12)"),
    ("college", "Community, technical, or vocational college"),
    ("higher-ed", "University"),
    ("non-accredited", "Informal non-accredited education"),
    ("lifelong", "Lifelong learning"),
    ("consortium", "Consortia Member"),
    ("consortium-org", "Consortia Organization"),
    ("initiative", "Open initiatives or special project"),
    ("commercial", "Corporate enterprise"),
    ("npo", "Non-profits, NGO’s, IGO"),
    ("cultural", "Cultural organization"),
    ("gov", "Government"),
)

ORGANIZATION_MEMBERSHIP_STATUS = (
    (1, "Applied"),
    (2, "Current"),
    (3, "Grace"),
    (4, "Expired"),
    (5, "Pending"),
    (6, "Cancelled"),
    (7, "Sustaining"),
    # (8,   'Deceased'),
    # (9,   'Testing'),
    # (10,'Committee'),
    # (11,'Committee'),
    # (12,'Suspended'),
    # (13,'New'),
    (99, "Example"),
)

ORGANIZATION_ASSOCIATED_CONSORTIUM = (
    ("CCCOER", "Community College Consortium for Open Educational Resources (CCCOER)"),
    ("CORE", "CORE"),
    ("JOCWC", "OE Japan"),
    ("KOCWC", "Korea OCW Consortium"),
    ("TOCEC", "Taiwan Open Course and Education Consortium"),
    ("Turkish OCWC", "Turkish OpenCourseWare Consortium"),
    ("UNIVERSIA", "UNIVERSIA"),
    ("FOCW", "Open Education France"),
    ("OTHER", "OTHER"),
)

ORGANIZATION_BILLING_TYPE = (
    ("normal", "Normal billing"),
    ("consortia", "Billed via Associate Consortia"),
    ("custom", "Custom Agreement"),
    ("waiver", "Fee waiver"),
)


class ActiveOrganizationManager(models.Manager):
    def get_queryset(self):
        return (
            super(ActiveOrganizationManager, self)
            .get_queryset()
            .filter(membership_status__in=(2, 3, 5, 7, 99))
            .order_by("display_name")
        )


class Organization(models.Model):
    legal_name = models.CharField(max_length=255, blank=True)
    display_name = models.CharField(
        max_length=255, verbose_name="Name of the organization"
    )
    slug = models.CharField(max_length=60, unique=True, default="")
    user = models.ForeignKey(User, models.CASCADE, blank=True, null=True)

    membership_type = models.IntegerField(choices=ORGANIZATION_MEMBERSHIP_TYPE_CHOICES)
    # organization_type = models.CharField(max_length=255, choices=ORGANIZATION_TYPE_CHOICES)
    membership_status = models.IntegerField(choices=ORGANIZATION_MEMBERSHIP_STATUS)
    billing_type = models.CharField(
        max_length=128, choices=ORGANIZATION_BILLING_TYPE, default="normal"
    )
    associate_consortium = models.CharField(
        max_length=255,
        choices=ORGANIZATION_ASSOCIATED_CONSORTIUM,
        blank=True,
        default="",
    )

    qbo_id = models.IntegerField(null=True, blank=True, default=None)

    main_website = models.URLField(max_length=255, blank=True)
    ocw_website = models.URLField(
        max_length=255, blank=True, verbose_name="OER/OCW Website"
    )

    description = models.TextField(blank=True)
    logo_large = models.ImageField(max_length=255, upload_to="logos", blank=True)
    logo_small = models.ImageField(max_length=255, upload_to="logos", blank=True)
    rss_course_feed = models.CharField(max_length=255, blank=True)

    accreditation_body = models.CharField(max_length=255, blank=True, default="")
    support_commitment = models.TextField(blank=True, default="")

    ocw_contact = models.ForeignKey(
        User,
        models.CASCADE,
        null=True,
        verbose_name="Primary contact inside OCW",
        related_name="ocw_contact_user",
        limit_choices_to={"is_staff": True},
    )

    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modified = models.DateTimeField(blank=True, auto_now=True)

    institution_type = models.CharField(
        max_length=25, blank=True, choices=INSTITUTION_TYPE_CHOICES, default=""
    )

    initiative_title1 = models.CharField(
        max_length=255, blank=True, default="", verbose_name="Initiative 1 Title"
    )
    initiative_description1 = models.TextField(
        blank=True,
        default="",
        verbose_name="Initiative 1 Description (100 – 350 characters)",
    )
    initiative_url1 = models.URLField(
        max_length=255, blank=True, default="", verbose_name="Initiative 1 URL"
    )

    initiative_title2 = models.CharField(
        max_length=255, blank=True, default="", verbose_name="Initiative 2 Title"
    )
    initiative_description2 = models.TextField(
        blank=True,
        default="",
        verbose_name="Initiative 2 Description (100 – 350 characters)",
    )
    initiative_url2 = models.URLField(
        max_length=255, blank=True, default="", verbose_name="Initiative 2 URL"
    )

    initiative_title3 = models.CharField(
        max_length=255, blank=True, default="", verbose_name="Initiative 3 Title"
    )
    initiative_description3 = models.TextField(
        blank=True,
        default="",
        verbose_name="Initiative 3 Description (100 – 350 characters)",
    )
    initiative_url3 = models.URLField(
        max_length=255, blank=True, default="", verbose_name="Initiative 3 URL"
    )

    individual_member = models.BooleanField(
        default=False, verbose_name="Individual member?"
    )
    org_affiliation = models.CharField(  # used only for individual members
        max_length=255,
        blank=True,
        default="",
        verbose_name="Organizational Affiliation",
    )

    objects = models.Manager()
    active = ActiveOrganizationManager()

    def __str__(self):
        return self.display_name

    def get_absolute_staff_url(self):
        return reverse("staff:organization-view", kwargs={"pk": self.id})

    def get_absolute_url(self):
        return reverse("crm:organization-view", kwargs={"pk": self.id})

    def get_logo_small_url(self):
        return "https://www.oeconsortium.org/media/%s" % self.logo_small

    def save(self, force_insert=False, force_update=False, using=None):
        if not self.slug:
            slug = slugify(self.display_name)[:30]
            if Organization.objects.filter(slug=slug).exists():
                slug = slug[:29] + "2"
            self.slug = slug

        super(Organization, self).save(
            force_insert=force_insert, force_update=force_update, using=using
        )

        if not self.qbo_id and self.membership_status != 1:
            try:
                qb_client, profile = Profile.get_qb_client()
                self.sync_quickbooks_customer(qb_client)
            except QuickbooksException as e:
                print(
                    "ERROR: unable to sync with QuickBooks: %s (org. ID: %d)"
                    % (e, self.id),
                    file=sys.stderr,
                )

    def get_membership_due_amount(self):
        # Sustaining members
        if self.membership_status in [7] or self.billing_type in [
            "custom",
            "consortia",
            "waiver",
        ]:
            return 0  # manually processed

        if self.associate_consortium == "CCCOER":
            return 650

        try:
            previous_invoice = self.billinglog_set.filter(

members/crm/templates/_application_moa_texts.html
<div style="display:none" class="moa">
    <p>We are pleased to cooperate with institutions, organizations and corporations around the world as members of Open Education Global.</p>
<p>As part of this cooperation, we agree to the following:
    <ol><li>We will demonstrate significant commitment to Open Education, for example, through the production, use and promotion of Open Educational Resources. Such demonstration can include the development and maintenance of an Open Education website that features open content consistent with the definition of Open Education on Open Education Global website, significant incorporation of Open Educational Resources into institutional offerings, active promotion of Open Educational practice, or other activity consistent with Open Education Global’s mission and values.</li>

    <li>We will work with other members to develop best practices to promote the development and use of OER and Open Educational practices. Opportunities to participate in working groups, committees and communities of interest are organized by OEG to facilitate these efforts.</li>

<li>We will pay annual membership dues. The schedule of membership fees per calendar year can be found on the OEG's website, and is subject to revision by the Consortium's Board of Directors and approved by active voting Members.
    <br />The applicable membership fee will be due upon the acceptance of our application as a member of Open Education Global.</li>
</ol>
</p>
<p>
        As long as we adhere to the above criteria, we understand that Open Education Global will allow us to display Open Education Global logo on our Open Education website. The logo will link directly to Open Education Global website. Additionally, Open Education Global will feature our logo and profile in the members list on the website, which will link to our Open Education website or other open initiative web page. We understand that Open Education Global can require us to remove Open Education Global logo from any and all of our sites, and will remove our name and logo from its website, should we no longer meet the criteria above.
</p>
</div>

members/crm/templates/_organization_info_full.html
		<div class="large-6 columns">
		{% if request.user.is_staff %}
			<h2>Account information</h2>
			<p>
				<strong>Last login:</strong> {{ org.user.last_login }}<br/>
			</p>
			<p>
				<strong>Type:</strong> {{ org.get_membership_type_display }} /
					{% if org.individual_member %}
						individual
					{% else %}
						organization
					{% endif %}
					<br />
				<strong>Status:</strong> {{ org.get_membership_status_display }}<br />
				{% if org.associate_consortium %}
					<strong>Associate consortium:</strong> {{ org.associate_consortium }}<br />
				{% endif %}
			</p>
		{% endif %}
		<h2 class="address">General information <a class="edit-link" href="{% url 'crm:organization-edit' org.id %}">Edit</a></h2>
		<p>
			<strong>Main website:</strong> <a href="{{ org.main_website }}">{{ org.main_website }}</a><br />
             {% if org.ocw_website %}
			    <strong>OER/OCW website:</strong> <a href="{{ org.ocw_website }}">{{ org.ocw_website }}</a><br />
             {% endif %}
		</p>
		<p class="org-description">
			{{ org.description }}
		</p>
		{% if org.logo_small %}
		<p>
			<img src="{{ MEDIA_URL }}{{ org.logo_small }}" />
		</p>
		{% endif %}
		{% for address in org.address_set.all %}
		<h2 class="address">{{ address.get_address_type_display }} <a class="edit-link" href="{% url 'crm:address-edit' address.id %}">Edit</a></h2>
		<p>
		   {{ address.street_address }}<br />
		   {% if address.supplemental_address_1 %}{{ address.supplemental_address_1 }}<br />{% endif %}
		   {% if address.supplemental_address_2 %}{{ address.supplemental_address_2 }}<br />{% endif %}

		   {{ address.city }}, {{ address.postal_code }} {{ address.postal_code_suffix }}<br />
		   {{ address.state_province }}, {{ address.country }}
		<p>
		{% endfor %}
		{% if request.user.is_staff %}
			<a href="/admin/crm/address/add/?organization={{ org.id }}" class="button buton-primary" target="_blank">Add Address</a>
		{% endif %}

        {% if org.initiative_description1 %}
            <h2>Initiatives</h2>
            {% if org.initiative_description1 %}
                <h3>Initiative 1: {{ org.initiative_title1 }}</h3>
                <p>{{ org.initiative_description1 }}</p>
                <a href="{{ org.initiative_url1 }}">{{ org.initiative_url1 }}</a><br /><br />
            {% endif %}

            {% if org.initiative_description2 %}
                <h3>Initiative 2: {{ org.initiative_title2 }}</h3>
                <p>{{ org.initiative_description2 }}</p>
                <a href="{{ org.initiative_url2 }}">{{ org.initiative_url2 }}</a><br /><br />
            {% endif %}

            {% if org.initiative_description3 %}
                <h3>Initiative 3: {{ org.initiative_title3 }}</h3>
                <p>{{ org.initiative_description3 }}</p>
                <a href="{{ org.initiative_url3 }}">{{ org.initiative_url3 }}</a><br /><br />
            {% endif %}
        {% endif %}
		</div>

		<div class="large-6 columns">
			<h2 class="contacts">Contacts</h2>
			{% for contact in org.contact_set.all %}
			<p>
				<strong>{{ contact.get_contact_type_display }}</strong><br />
            {% if contact.job_title %}<strong>Job Title:</strong> {{ contact.job_title }}<br />{% endif %}
				<strong>Name:</strong> {{ contact.first_name }} {{ contact.last_name }}<br />
				<strong>Email:</strong> {{ contact.email }}
				{% if contact.bouncing %}<span class="warning">(bounces!)</span>{% endif %}
			</p>
			{% endfor %}
			{% if not user.is_staff %}
			<p>To update information on who can access and vote on behalf of your organization, please contact <a href="mailto:memberservices@oeglobal.org">member services</a>.</p>
			{% endif %}
		</div>
		<div class="large-6 columns">
			{% if org.get_consortia_members.count %}
			<h2>{{ org.get_consortia_members.count }} Consortia Members</h2>
			<ul>
				{% for consortia_member in org.get_consortia_members.all %}
					<li><a href="{{ consortia_member.get_absolute_url }}">{{ consortia_member.display_name }}</a></li>
				{% endfor %}
			</ul>
			{% endif %}
		</div>
		{% if user.is_staff %}
		<div class="large-6 columns">
			<hr/>
			<p>
				<strong>Created:</strong> {{org.created}}<br/>
				<strong>Modified:</strong> {{org.modified}}
			</p>
		</div>
		{% endif %}

members/crm/templates/address_edit.html
{% extends "base.html" %}

{% block contents %}
	<div class="row">
		<div class="large-6 columns">
			<form action="" method="POST">
				{% csrf_token %}	
				{{ form.as_p }}
				<input type="submit" class="button" value="Submit">
			</form>
		</div>
	</div>
{% endblock %}

members/crm/templates/membership_application_list.html
{% extends "base.html" %}

{% block contents %}
<div class="row">
	<div class="large-12 columns">
		<table>
			<thead>
				<tr>
					<th>Institution name</th>
					<th>Submitted</th>
					<th>Updated</th>
					<th>Status</th>
				</tr>
			</thead>
		{% for app in object_list %}
			<tr>
				<td><a href="{{ app.get_absolute_url }}">
					{% if app.organization %}{{ app.organization }}
					{% elif app.display_name %}{{ app.display_name }}
					{% else %}Application #{{ app.id }}
					{% endif %}
					</a></td>
				<td>{{ app.created }}</td>
				<td>{{ app.modified }}</td>
				<td>{{ app.get_app_status_display }}</td>
			</tr>
		{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

members/crm/templates/membership_application_view.html
{% extends "base.html" %}

{% block contents %}
    <div class="row">
        <div class="large-12 columns">
            <h3>Institutional Membership Application Received</h3>
            <h1>{{ app.display_name }}</h1>
            <p>Thank you for submitting an application for {{ app.display_name }} to become an institutional member of Open Education Global.</p>
            <p>You can expect a response from one of our team members within a week. Upon approval of membership, we will reply by email with
            a welcome message including details on the next steps to activate your membership including notice of  the amount and date due for
            your membership, sent separately as an invoice.</p>
            <p>Please note that newly approved members only become official OEGlobal members upon receipt of the annual membership fee payment.</p>
        </div>
    </div>

    <div class="row">
        <div class="large-8 columns">
            <h2>Membership</h2>
            <p>
                {% if app.simplified_membership_type %}
                    <strong>Type:</strong> {{ app.get_simplified_membership_type_display }}<br/>
                    {% if app.simplified_membership_type == 'institutional' %}
                        <strong>Consortia:</strong> {{ app.get_associate_consortium_display }}<br/>
                    {% endif %}
                    {% if app.simplified_membership_type == 'corporate' %}
                        <strong>Support level:</strong> {{ app.get_corporate_support_levels_display }}<br/>
                    {% endif %}
                {% endif %}
                {% if app.associate_consortium %}
                    <strong>Consortia:</strong> {{ app.get_associate_consortium_display }}<br/>
                {% endif %}
            </p>
            <p>
                <strong>Submitted on:</strong> {{ app.created|date:"M. j, Y" }}<br/>
                <strong>Last updated on:</strong> {{ app.modified|date:"M. j, Y" }}<br/>
                <strong>Status:</strong> {{ app.get_app_status_display }}<br/>
            </p>
            <h2>Support Commitment</h2>
            <p>{{ app.support_commitment }}</p>

            <h2>Initiatives</h2>
            <strong>Initiative 1: {{ app.initiative_title1 }}</strong><br />
            <p>{{ app.initiative_description1 }}</p>
            <p>{{ app.initiative_url1 }}</p><br /><br />

            <strong>Initiative 2: {{ app.initiative_title2 }}</strong><br />
            <p>{{ app.initiative_description2 }}</p>
            <p>{{ app.initiative_url2 }}</p>

            <strong>Initiative 3: {{ app.initiative_title3 }}</strong><br />
            <p>{{ app.initiative_description3 }}</p>
            <p>{{ app.initiative_url3 }}</p>

            <h2>Member Profile</h2>
            <p>
                <strong>Name:</strong> {{ app.display_name }}<br/>
                <strong>Description:</strong> {{ app.description }}<br/>

                {% if app.institution_type %}
                    <strong>Institution Category:</strong> {{ app.get_institution_type_display }}<br/>
                {% else %}
                    <strong>Institution Category:</strong> {{ app.get_organization_type_display }}<br/>
                    <strong>Is accredited:</strong> {{ app.get_is_accredited_display }}<br/>
                    <strong>Accreditation body:</strong> {{ app.accreditation_body }}<br/>
                {% endif %}

                {% if app.logo_large %}
                    <strong>Logo was provided</strong>
                {% else %}
                    <strong>Logo not provided</strong>
                {% endif %}
            </p>
            <p>
                <strong>Main Website:</strong> {{ app.main_website }}<br/>
                <strong>OCW Website:</strong>
                {{ app.ocw_website }}<br/>
            </p>
            <h2>Address</h2>
            <p>
                {{ app.street_address }}<br/>
                {% if app.supplemental_address_1 %}{{ app.supplemental_address_1 }}<br/>{% endif %}
                {% if app.supplemental_address_2 %}{{ app.supplemental_address_1 }}<br/>{% endif %}
                {{ app.postal_code }} {{ app.city }}<br/>
                {{ app.state_province }}<br/>
                {{ app.country }}<br/>
            </p>
            <h2>Lead Contact Information</h2>
            <p>
                <strong>First name:</strong> {{ app.first_name }}<br/>
                <strong>Last name:</strong> {{ app.last_name }}<br/>
                <strong>Job title:</strong> {{ app.job_title }}<br/>
                <strong>Email:</strong> <a href="mailto:{{ app.email }}">{{ app.email }}</a><br/>
            </p>
        </div>
        <div class="large-4 columns">
            <p>If you have any questions or need an update on your application, please contact us at
            <a href="mailto:memberservices@oeglobal.org">memberservices@oeglobal.org</a>.</p>
            {% if user.is_staff %}
                <a href="/admin/crm/membershipapplication/{{ app.id }}/" class="button">Edit Application</a>
            {% endif %}
            <p>
        </div>
    </div>
{% endblock %}

members/crm/templates/overview_index.html
{% extends "base.html" %}

{% block contents %}
    <div class="row">
        <div class="small-12 columns">
            <h1>{{ org.display_name }}</h1>

            <ul>
                <li><a href="{% url 'crm:organization-view' org.id %}">View organization information</a></li>
                <li><a href="{% url 'crm:reported-statistics-view' org.id %}">Report course statistics</a></li>
            </ul>
        </div>


        {% comment %}
            <div class="small-12 columns">
                <h2>Membership</h2>
                <p><a href="https://www.oeconsortium.org/members/member-mark/" target="_blank" class="button">Implement
                    new Member Mark</a></p>
            </div>
        {% endcomment %}

        {#{% comment %}#}
        {% now "Y-m-d H:i:s" as current_time %}
        {% if current_time < "2024-09-26 23:59:59" %}
        <div class="large-12 columns">
            <h1>Elections</h1>
            {# <p>Voting period has ended.</p> #}


            {% if org.can_vote %}
                <p>We invite you to <a href="https://www.oeglobal.org/about-us/elections/" target="_blank">review the
                    biography of candidates</a>.</p>
                <p>
                    <a href="{% url 'elections:vote-add' 12 %}" class="button medium">Vote in the Elections</a>
                </p>
            {% else %}
                <p>You are currently not eligible to vote. Please contact <a
                        href="mailto:memberservices@oeglobal.org">memberservices@oeglobal.org</a> for details.</p>
            {% endif %}
        </div>
        {% endif %}
        {#{% endcomment %}#}

    </div>
{% endblock %}

members/crm/templates/reported_statistic_view.html
{% extends "base.html" %}

{% block contents %}
	<div class="row">
		<div class="large-12 columns">
			<h1>{{ org.display_name }}</h1>
		</div>
		<h2>Statistics</h2>
		<p><a class="button medium" href="{% url 'crm:reported-statistics-add' org.id %}">Report new statistic</a></p>
		<table>
			<tr>
				<th>Date</th>
				<th>Original courses</th>
				<th>O. course language</th>
				<th>Translated courses</th>
				<th>T. courses language</th>
				<th>OER resources</th>
				<th>T. OER resources</th>
				<th>Comment</th>
			</tr>
		{% for stat in statistic_list %}
			<tr>
				<td><a href="{% url 'crm:reported-statistics-edit' stat.id %}">{{ stat.report_date }}</td>
				<td>{{ stat.orig_courses }}</td>
				<td>{{ stat.trans_courses }}</td>
				<td>{{ stat.orig_course_lang }}</td>
				<td>{{ stat.trans_course_lang }}</td>
				<td>{{ stat.oer_resources }}</td>
				<td>{{ stat.trans_oer_resources }}</td>
				<td>{{ stat.comment }}</td>
			</tr>
		{% endfor %}
		</table>
		<a href="{% url 'crm:reported-statistics-add' org.id %}" class="button medium">Report new statistic</a>
	</div>
{% endblock %}