members/crm/urls.py
from django.urls import path

from .views import OrganizationIndex, OrganizationDetailView, OrganizationEdit, \
    ReportedStatisticDetailView, ReportedStatisticEditView, ReportedStatisticAddView, \
    AddressEditView

from vanilla import TemplateView

app_name = 'crm'
urlpatterns = [
    path('member/view/<int:pk>/', OrganizationDetailView.as_view(), name='organization-view'),
    path('member/edit/<int:pk>/', OrganizationEdit.as_view(), name='organization-edit'),
    path('member/address/edit/<int:pk>/', AddressEditView.as_view(), name='address-edit'),
    path('member/statistics/view/<int:pk>/', ReportedStatisticDetailView.as_view(),
        name='reported-statistics-view'),
    path('member/statistics/edit/<int:pk>/', ReportedStatisticEditView.as_view(), name='reported-statistics-edit'),
    path('member/statistics/add/<int:pk>/', ReportedStatisticAddView.as_view(), name='reported-statistics-add'),
    path('', OrganizationIndex.as_view(), name='index'),
]

members/elections/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import (
    CandidateAddView,
    CandidateEditView,
    CandidateView,
    ElectionListView,
    VoteView,
    VoteAddFormView,
    VoteResults,
)
from .api import ElectionCandidatesListAPIView

app_name = "elections"
urlpatterns = [
    path("candidate/nominate/", CandidateAddView.as_view(), name="candidate-add"),
    path(
        "candidate/edit/<str:key>/",
        CandidateEditView.as_view(lookup_field="edit_link_key", lookup_url_kwarg="key"),
        name="candidate-edit",
    ),
    path(
        "candidate/view/<str:key>/",
        CandidateView.as_view(lookup_field="view_link_key", lookup_url_kwarg="key"),
        name="candidate-view",
    ),
    path(
        "candidate/list/<str:key>/",
        ElectionListView.as_view(
            lookup_field="view_nominations_key", lookup_url_kwarg="key"
        ),
        name="candidate-list",
    ),
    path(
        "api/candidate/list/<str:key>/",
        ElectionCandidatesListAPIView.as_view(),
        name="api-candidate-list",
    ),
    path("vote/add/<int:pk>/", VoteAddFormView.as_view(), name="vote-add"),
    path("vote/<int:pk>/", VoteView.as_view(), name="vote-view"),
    path("vote/results/", VoteResults.as_view(), name="vote-results"),
]

members/members/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static

from django.contrib import admin
from django.views.static import serve
from crm.views import IndexView, LoginKeyCheckView

admin.autodiscover()

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("api/v1/", include("crm.urls_api")),
    path("crm/", include("crm.urls")),
    path("staff/", include("crm.urls_staff")),
    path("application/", include("crm.urls_application")),
    path(
        "login/<str:key>/",
        LoginKeyCheckView.as_view(),
        name="login-key-check",
    ),
    path("conferences/", include("conferences.urls")),
    path("elections/", include("elections.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("", IndexView.as_view(), name="crm_index"),
]

if settings.DEBUG:
    urlpatterns += [
        path(
            "media/logos/<path:path>",
            serve,
            {"document_root": settings.MEDIA_ROOT + '/logos/'},
        ),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/elections/models.py
# -*- coding: utf-8 -*-
import uuid

from django.db import models
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.core.validators import validate_comma_separated_integer_list

from crm.models import Organization


class Election(models.Model):
    title = models.CharField(max_length=255)
    view_nominations_key = models.CharField(max_length=255, blank=True)
    edit_nominations_key = models.CharField(max_length=255, blank=True)

    nominate_until = models.DateTimeField(null=True)
    vote_from = models.DateTimeField(null=True)
    vote_until = models.DateTimeField(null=True)

    class Meta:
        get_latest_by = "pk"

    def save(self, force_insert=False, force_update=False, using=None):
        if not self.view_nominations_key:
            self.view_nominations_key = uuid.uuid4().hex
        if not self.edit_nominations_key:
            self.edit_nominations_key = uuid.uuid4().hex
        super(Election, self).save(
            force_insert=force_insert, force_update=force_update, using=using
        )

    def __str__(self):
        return self.title


CANDIDATE_STATUS_CHOICES = (
    ("nominated", "Nominated"),
    ("accepted", "Accepted"),
    ("declined", "Declined"),
    ("rejected", "Rejected"),
    ("spam", "Spam"),
)

SEAT_TYPE_CHOICES = (
    ("institutional", "Institutional"),
    ("organizational", "Organizational"),
)

EXPERTISE_CHOICES = (
    (1, "Fundraising & Sustainability"),
    (2, "Membership Growth and Engagement"),
    (3, "Events and Services"),
    (4, "Operations including Legal & Finance"),
    (5, "Other"),
)


class Candidate(models.Model):
    election = models.ForeignKey(Election, models.CASCADE)
    status = models.CharField(
        max_length=60, choices=CANDIDATE_STATUS_CHOICES, default=""
    )

    candidate_first_name = models.CharField(max_length=255)
    candidate_last_name = models.CharField(max_length=255)
    candidate_job_title = models.CharField(max_length=255, blank=True, default="")
    candidate_email = models.EmailField(max_length=255)
    candidate_phone_number = models.CharField(max_length=255, blank=True, default="")

    reason = models.TextField(blank=True)
    # organization = models.CharField(max_length=255)
    organization = models.ForeignKey(Organization, models.CASCADE)

    sponsor_first_name = models.CharField(max_length=255)
    sponsor_last_name = models.CharField(max_length=255)
    sponsor_email = models.CharField(max_length=255)

    edit_link_key = models.CharField(max_length=255, blank=True)
    view_link_key = models.CharField(max_length=255, blank=True)

    email_alternate = models.CharField(max_length=255, blank=True, default="")
    biography = models.TextField(blank=True)
    vision = models.TextField(blank=True)
    ideas = models.TextField(blank=True)

    external_url = models.CharField(max_length=255, blank=True, default="")

    vetted = models.BooleanField(default=False)
    seat_type = models.CharField(max_length=60, choices=SEAT_TYPE_CHOICES, blank=True)

    pub_date = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    order = models.IntegerField(default=0)

    expertise = models.TextField(
        default="", validators=[validate_comma_separated_integer_list], blank=True
    )
    expertise_other = models.CharField(default="", max_length=255, blank=True)
    expertise_expanded = models.TextField(default="", blank=True)

    agreement_cost = models.BooleanField(default=False)
    agreement_fund = models.BooleanField(default=False)

    def get_absolute_edit_url(self):
        return reverse("elections:candidate-edit", kwargs={"key": self.edit_link_key})

    def save(self, force_insert=False, force_update=False, using=None):
        if not self.edit_link_key:
            self.edit_link_key = uuid.uuid4().hex
        if not self.view_link_key:
            self.view_link_key = uuid.uuid4().hex
        super(Candidate, self).save(
            force_insert=force_insert, force_update=force_update, using=using
        )

    def email_board(self):
        try:
            send_mail(
                "{candidate.candidate_first_name} {candidate.candidate_last_name} was nominated for OEG Board".format(
                    candidate=self
                ),
                render_to_string(
                    "elections/email_candidate_board_body.txt", {"candidate": self}
                ),
                "tech@oeglobal.org",
                [settings.NOMINATION_COMMITTEE_EMAIL],
            )
        except (Exception, ConnectionRefusedError) as e:
            print("ERROR: failed to send email: %s" % e)

    def email_candidate(self):
        try:
            send_mail(
                "You have been nominated to serve on the OEG Board of Directors",
                render_to_string(
                    "elections/email_candidate_nominee_body.txt", {"candidate": self}
                ),
                "tech@oeglobal.org",
                [self.candidate_email],
            )
        except (Exception, ConnectionRefusedError) as e:
            print("ERROR: failed to send email: %s" % e)

    def get_expertise_items(self):
        expertise_list = self.expertise.split(",")
        choices = dict(EXPERTISE_CHOICES)
        items = []
        for expertise in expertise_list:
            try:
                items.append(choices[int(expertise)])
            except ValueError:
                print(
                    'WARNING: unable to parse expertise "%s" for candidate id=%s'
                    % (expertise, self.id)
                )

        return items

    def __str__(self):
        return "%s %s (%s)" % (
            self.candidate_first_name,
            self.candidate_last_name,
            self.organization.display_name,
        )


class CandidateBallot(models.Model):
    election = models.ForeignKey(Election, models.CASCADE)
    organization = models.ForeignKey(Organization, models.CASCADE)
    voter_name = models.CharField(max_length=255)

    seat_type = models.CharField(max_length=60, choices=SEAT_TYPE_CHOICES)
    votes = models.ManyToManyField(Candidate)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class Proposition(models.Model):
    election = models.ForeignKey(Election, models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    published = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


PROPOSITION_CHOICES = (
    (True, mark_safe("We vote <strong>for</strong> this proposition")),
    (False, mark_safe("We vote <strong>against</strong> this proposition")),
    (None, mark_safe("We abstain")),
)


class PropositionBallot(models.Model):
    election = models.ForeignKey(Election, models.CASCADE)
    proposition = models.ForeignKey(Proposition, models.CASCADE)

    organization = models.ForeignKey(Organization, models.CASCADE)
    voter_name = models.CharField(max_length=255)

    vote = models.BooleanField(null=True, choices=PROPOSITION_CHOICES)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

members/elections/views.py
# -*- coding: utf-8 -*-
import datetime
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import Http404

from vanilla import UpdateView, DetailView, ListView, FormView, TemplateView
from braces.views import LoginRequiredMixin, StaffuserRequiredMixin

from .forms import CandidateAddForm, CandidateEditForm, VoteForm
from .models import Candidate, Election, PropositionBallot, CandidateBallot

from crm.models import Organization


class StaffView(LoginRequiredMixin, StaffuserRequiredMixin):
    pass


class CandidateAddView(FormView):
    form_class = CandidateAddForm
    template_name = "elections/candidate_add.html"

    def dispatch(self, request, *args, **kwargs):
        election = Election.objects.latest("id")
        if election.nominate_until < datetime.datetime.now():
            return render(self.request, "elections/election_closed_nominations.html")

        return super(CandidateAddView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        org = Organization.objects.get(pk=form.cleaned_data.get("organization"))
        del form.cleaned_data["organization"]
        del form.cleaned_data["terms"]

        candidate = Candidate(**form.cleaned_data)
        candidate.election = Election.objects.latest("id")
        candidate.organization = org
        candidate.save()

        candidate.email_board()
        candidate.email_candidate()

        return render(self.request, "elections/candidate_add_success.html")


class CandidateEditView(UpdateView):
    form_class = CandidateEditForm
    model = Candidate
    template_name = "elections/candidate_edit.html"

    def get_success_url(self):
        return self.object.get_absolute_edit_url()


class CandidateView(DetailView):
    model = Candidate
    template_name = "elections/candidate_view.html"
    context_object_name = "candidate"


class ElectionListView(ListView):
    model = Election
    template_name = "elections/candidate_list.html"
    context_object_name = "election"


class VoteView(LoginRequiredMixin, DetailView):
    model = Election
    template_name = "elections/vote_view.html"
    context_object_name = "election"

    def get_context_data(self, **kwargs):
        context = super(VoteView, self).get_context_data(**kwargs)

        org = Organization.objects.get(user=self.request.user)

        context["proposition_votes"] = PropositionBallot.objects.filter(
            organization=org, election=context["election"]
        ).order_by("proposition__title")
        context["candidate_votes"] = CandidateBallot.objects.filter(
            organization=org, election=context["election"]
        )

        if (
            self.object.propositionballot_set.filter(organization=org).count()
            < org.get_number_of_votes()
        ):
            context["organization"] = org
            context["show_vote_button"] = True

        return context


class VoteAddFormView(LoginRequiredMixin, FormView):
    form_class = VoteForm
    template_name = "elections/vote_form.html"

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous():
            raise Http404

        self.election = Election.objects.get(pk=kwargs.pop("pk"))
        self.organization = Organization.objects.get(user=self.request.user)

        if not self.organization.can_vote():
            raise Http404

        if self.election.candidateballot_set.filter(
            seat_type="institutional", organization=self.organization
        ).count():
            return redirect(
                reverse("elections:vote-view", kwargs={"pk": self.election.id})
            )

        return super(VoteAddFormView, self).dispatch(request, *args, **kwargs)

    def get_form(self, data=None, files=None, **kwargs):
        kwargs["election"] = self.election
        return self.get_form_class()(data, files, **kwargs)

    def form_valid(self, form):
        cleaned_data = form.cleaned_data

        propositions = self.election.proposition_set.filter(published=True).order_by(
            "title"
        )
        if propositions:
            for i in range(len(propositions)):
                proposition = propositions[i]
                proposition_vote = cleaned_data.get("proposition_vote%d" % (i + 1))
                if proposition_vote == "yes":
                    vote = True
                elif proposition_vote == "no":
                    vote = False
                else:
                    vote = None

                PropositionBallot.objects.create(
                    proposition=proposition,
                    election=self.election,
                    organization=self.organization,
                    vote=vote,
                    voter_name=cleaned_data.get("name"),
                )

        institutional_ballot = CandidateBallot.objects.create(
            election=self.election,
            organization=self.organization,
            voter_name=cleaned_data.get("name"),
            seat_type="institutional",
        )

        for candidate_id in cleaned_data.get("institutional_candidates"):
            candidate = Candidate.objects.get(pk=candidate_id)
            institutional_ballot.votes.add(candidate)

        # organizational_ballot = CandidateBallot.objects.create(
        #     election=self.election,
        #     organization=self.organization,
        #     voter_name=cleaned_data.get('name'),
        #     seat_type='organizational'
        # )
        #
        # for candidate_id in cleaned_data.get('organizational_candidates'):
        #     candidate = Candidate.objects.get(pk=candidate_id)
        #     organizational_ballot.votes.add(candidate)

        return redirect(reverse("elections:vote-view", kwargs={"pk": self.election.id}))


class VoteResults(StaffView, TemplateView):
    def get(self, request, *args, **kwargs):
        election = Election.objects.latest("pk")
        ballots = CandidateBallot.objects.filter(election=election).order_by(
            "organization__display_name"
        )

        ctx = {"election": election, "ballots": ballots}

        return render(self.request, "elections/vote_results.html", ctx)

members/elections/templates/elections/base.html
{% extends "base.html" %}

members/elections/templates/elections/candidate_add.html
{% extends "elections/base.html" %}{% load crispy_forms_tags %}{% load static %}

{% block extra_head %}
	<link href="{% static 'uni-form/css/uni-form.css' %}" media="screen, projector, print" rel="stylesheet" type="text/css" />
	<link href="{% static 'uni-form/css/default.uni-form.css' %}" media="screen, projector, print" rel="stylesheet" type="text/css" />

	<style type="text/css">
		input[type="email"] {
			width: 53%;
		}

		.terms ul, .terms p {
			width: 100%;
			margin-left: 1em;
		}
		.terms ul li {
			list-style: disc inside;
		}

		label[for="id_terms"] {
			display: inline-block;
		}

        #div_id_expertise > label {
            margin-bottom: 10px;
        }

        .checkboxselectmultiple {
            font-size: 16px;
        }
	</style>
{% endblock %}

{% block contents %}
	<div class="row">
		<div class="large-8 columns">
			<form method="POST" action="" class="uniForm">
				{{ form|as_crispy_errors }}
				{% crispy form %}
			</form>
		</div>
	</div>
{% endblock %}

members/elections/templates/elections/candidate_add_success.html
{% extends "elections/base.html" %}

{% block contents %}
	<div class="row">
		<div class="large-8 columns">
			<h1>Thank you for submitting your nomination</h1>
			<p>We will notify candidate and board of directors.</p>
		</div>
	</div>
{% endblock %}

members/elections/templates/elections/candidate_edit.html
{% extends "elections/base.html" %}{% load crispy_forms_tags %}{% load static %}

{% block extra_head %}
	<link href="{% static 'uni-form/css/uni-form.css' %}" media="screen, projector, print" rel="stylesheet" type="text/css" />
	<link href="{% static 'uni-form/css/default.uni-form.css' %}" media="screen, projector, print" rel="stylesheet" type="text/css" />

	<style type="text/css">
		input[type="email"] {
			width: 53%;
		}

		.terms ul, .terms p {
			width: 100%;
			margin-left: 1em;
		}
		.terms ul li {
			list-style: disc inside;
		}

		label[for="id_terms"] {
            display: inline-block;

        }

        #id_agreement_cost,
        #id_agreement_fund {
            margin-right: 5px;
            margin-bottom: 5px;
        }

        label[for="id_agreement_cost"],
        label[for="id_agreement_fund"]{
            display: inline;
        }
	</style>
{% endblock %}

{% block extra_foot %}
    <script>
    jQuery(document).ready(function() {
        var checkOther = function() {
            if ($('#id_expertise_4').is(':checked')) {
                $('#id_expertise_other').attr('required', true);
            } else {
                $('#id_expertise_other').attr('required', false);
            }
        }

        $('#id_expertise_4').on('change', checkOther);
        checkOther();
    });
    </script>
{% endblock %}

{% block contents %}
	<div class="row">
		<div class="large-8 columns">
			{% if form.initial.acceptance %}
			<div class="alert-box">
				We have received your Candidacy for Board of Directors. You can further revise it below.
			</div>
			{% endif %}
			<form method="POST" action="" class="uniForm">
				{{ form|as_crispy_errors }}
				{% crispy form %}
			</form>
		</div>
	</div>
{% endblock %}

members/elections/templates/elections/candidate_list.html
{% extends "elections/base.html" %}

{% block contents %}

<div class="row">
	<div class="large-12 columns">
		<table>
			<thead>
				<tr>
					<th>Name</th>
					<th>Organization</th>
					<th>Status</th>
					<th>Details</th>
				</tr>
			</thead>
			<tbody>
				<h3>Nominees for Board of Directors</h3>
				{% for candidate in election.latest.candidate_set.all %}
					<tr>
						<td>{{ candidate.candidate_first_name }} {{ candidate.candidate_last_name }}</td>
						<td>{{ candidate.organization.display_name }}</td>
						<td>{{ candidate.get_status_display }}</td>
						<td><a href="{% url 'elections:candidate-view' key=candidate.view_link_key %}">View details</a>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

{% endblock %}

members/elections/templates/elections/candidate_view.html
{% extends "elections/base.html" %}

{% block contents %}
    <div class="row">
        <div class="large-8 columns">
            <h3>Nomination Information</h3>
            <dd>Nominated by:</dd>
            <dt>{{ candidate.sponsor_first_name }} {{ candidate.sponsor_last_name }} ({{ candidate.sponsor_email }})
            </dt>
            <dd>Reason for Nomination:</dd>
            <dt>{{ candidate.reason }}</dt>
        </div>
    </div>
    <div class="row">
        <div class="large-8 columns">
            <h3>Status</h3>
            <dd>Status:</dd>
            <dt>{{ candidate.get_status_display }}</dt>
            <dd>Vetted:</dd>
            <dt>{{ candidate.get_vetted_display }}</dt>
            <dd>Seat type:</dd>
            <dt>{{ candidate.get_seat_type }}</dt>

            <dd>Submitted:</dd>
            <dt>{{ candidate.pub_date }}</dt>
            <dd>Last modified:</dd>
            <dt>{{ candidate.last_modified }}</dt>
        </div>
    </div>
    <div class="row">
        <div class="large-8 columns">
            <h3>About the Nominee</h3>

            <dd>Name:</dd>
            <dt>{{ candidate.candidate_first_name }} {{ candidate.candidate_last_name }}</dt>
            <dd>Job title:</dd>
            <dt>{{ candidate.candidate_job_title }}</dt>
            <dd>Organization:</dd>
            <dt>{{ candidate.organization.display_name }}</dt>
            <dd>E-mail:</dd>
            <dt>{{ candidate.candidate_email }}</dt>
            <dd>Alternative e-mail:</dd>
            <dt>{{ candidate.email_alternate }}</dt>
            <dd>Phone number:</dd>
            <dt>{{ candidate.candidate_phone_number }}</dt>

            <dd>Biography:</dd>
            <dt>{{ candidate.biography }}</dt>
            <dd>Vision:</dd>
            <dt>{{ candidate.vision }}</dt>
            <dd>Ideas:</dd>
            <dt>{{ candidate.ideas }}</dt>
            <dd>Expertise:</dd>
            <dt>{{ candidate.get_expertise_items|join:', ' }}</dt>
            <dd>Expertise Other:</dd>
            <dt>{{ candidate.expertise_other }}</dt>
            <dd>Expertise (Expanded):</dd>
            <dt>{{ candidate.expertise_expanded }}</dt>
            <dd>External url:</dd>
            <dt>{{ candidate.external_url }}</dt>
        </div>
    </div>
{% endblock %}

members/elections/templates/elections/election_closed_nominations.html
{% extends "elections/base.html" %}

{% block contents %}
	<div class="row">
		<div class="large-8 columns">
			<h2>Nominations are now closed</h2>
			<p>Thank you for your interest in Board Elections. Nominations are now closed.</p>
		</div>
	</div>
{% endblock %}

members/elections/templates/elections/vote_form.html
{% extends "elections/base.html" %}{% load crispy_forms_tags %}{% load static %}

{% block extra_head %}
	<link href="{% static 'uni-form/css/uni-form.css' %}" media="screen, projector, print" rel="stylesheet" type="text/css" />
	<link href="{% static 'uni-form/css/default.uni-form.css' %}" media="screen, projector, print" rel="stylesheet" type="text/css" />
{% endblock %}

{% block contents %}
	<div class="row">
		<div class="large-12 columns">
			<form action="" method="POST">
				{{ form|as_crispy_errors }}
				{% crispy form %}
			</form>
		</div>
	</div>
{% endblock %}

members/elections/templates/elections/vote_results.html
{% extends "elections/base.html" %}

{% block contents %}
	<div class="row">
		<div class="large-12 columns">
            <h2>{{ election.title }}</h2>
            <ul>
            {% for ballot in ballots %}
                <li><strong>{{ ballot.organization.display_name }}</strong> by <i>{{ ballot.voter_name }}</i></li>
            {% endfor %}

            <br />
            <p>Total ballots cast: {{ ballots.count }}</p>
            </ul>
		</div>
	</div>
{% endblock %}

members/elections/templates/elections/vote_view.html
{% extends "elections/base.html" %}

{% block contents %}
	<div class="row">
		<div class="large-12 columns">
			<h2>Thank you for voting in {{ election.title }}.</h2>

			<p>Your vote:</p>
			{% if proposition_votes %}
				<ul>
				{% for vote in proposition_votes %}
					<li><em>{{ vote.voter_name }}</em> voted in {{ vote.proposition.title }}: <br /><strong>{{ vote.get_vote_display }}</strong></li>
				{% endfor %}
				</ul>
			{% endif %}

			{% if candidate_votes %}
			<ul>
                {% for vote in candidate_votes %}
				<li>For Board of Directors: <br />
					{% for candidate in vote.votes.all %}
						<strong>{{ candidate.candidate_first_name }} {{ candidate.candidate_last_name }}</strong>{% if not forloop.last %}, {% endif %}
					{% endfor %}
				</li>
				{% endfor %}
                {% with candidate_votes|first as vote %}
                    <em>Vote was cast by {{ vote.voter_name }}</em>.
                {% endwith %}
			</ul>
			{% endif %}
			
		</div>

{#		{% if show_vote_button %}#}
{#			<p>You can cast {{ organization.get_number_of_votes }} votes, so we invite you to vote again, each ballot is one vote: <br />#}
{#				<a href="{% url 'elections:vote-add' 5 %}" class="button medium">Vote in 2017 Elections - Run Off</a>#}
{#			</p>#}
{#		{% endif %}#}
	</div>
{% endblock %}