members/conferences/urls.py
from django.urls import path

from .views import (
    ConferenceIndex,
    InvoicePDF,
    InvoicePreview,
    PingInvoices,
    ConnectEmail,
)

app_name = "conferences"
urlpatterns = [
    path("", ConferenceIndex.as_view(), name="index"),
    path("invoice/ping/", PingInvoices.as_view(), name="invoice_ping"),
    path("invoice/<int:pk>/", InvoicePDF.as_view(), name="invoice_download"),
    path(
        "invoice/<int:pk>/<str:access_key>/",
        InvoicePreview.as_view(),
        name="invoice_preview",
    ),
    path("connect/", ConnectEmail.as_view(), name="connect_email"),
]

members/crm/urls.py
from django.urls import path

from .views import OrganizationIndex, OrganizationDetailView, OrganizationEdit, \
    ReportedStatisticDetailView, ReportedStatisticEditView, ReportedStatisticAddView, \
    AddressEditView

from vanilla import TemplateView

app_name = 'crm'
urlpatterns = [
    path('member/view/<int:pk>/', OrganizationDetailView.as_view(), name='organization-view'),
    path('member/edit/<int:pk>/', OrganizationEdit.as_view(), name='organization-edit'),
    path('member/address/edit/<int:pk>/', AddressEditView.as_view(), name='address-edit'),
    path('member/statistics/view/<int:pk>/', ReportedStatisticDetailView.as_view(),
        name='reported-statistics-view'),
    path('member/statistics/edit/<int:pk>/', ReportedStatisticEditView.as_view(), name='reported-statistics-edit'),
    path('member/statistics/add/<int:pk>/', ReportedStatisticAddView.as_view(), name='reported-statistics-add'),
    path('', OrganizationIndex.as_view(), name='index'),
]

members/members/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static

from django.contrib import admin
from django.views.static import serve
from crm.views import IndexView, LoginKeyCheckView

admin.autodiscover()

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("api/v1/", include("crm.urls_api")),
    path("crm/", include("crm.urls")),
    path("staff/", include("crm.urls_staff")),
    path("application/", include("crm.urls_application")),
    path(
        "login/<str:key>/",
        LoginKeyCheckView.as_view(),
        name="login-key-check",
    ),
    path("conferences/", include("conferences.urls")),
    path("elections/", include("elections.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("", IndexView.as_view(), name="crm_index"),
]

if settings.DEBUG:
    urlpatterns += [
        path(
            "media/logos/<path:path>",
            serve,
            {"document_root": settings.MEDIA_ROOT + '/logos/'},
        ),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/conferences/models.py
# -*- coding: utf-8 -*-
import uuid
from tinymce.models import HTMLField

from django.db import models
from django.urls import reverse
from django.core.mail import EmailMessage
from django.conf import settings
from django.db.models import JSONField

from crm.utils import print_pdf


class ConferenceInterface(models.Model):
    name = models.CharField(max_length=255)
    url = models.CharField(max_length=255, default="")
    api_key = models.CharField(max_length=255, default="")
    private_key = models.CharField(max_length=255, default="")

    last_synced = models.DateTimeField(null=True)

    def __str__(self):
        return self.name


class ConferenceRegistration(models.Model):
    PAYMENT_TYPE = (("paypal", "PayPal"), ("wire", "Wire Transfer"))

    interface = models.ForeignKey(ConferenceInterface, models.CASCADE)
    form_id = models.CharField(max_length=255)
    entry_id = models.CharField(max_length=255)
    entry_created = models.DateTimeField(null=True)

    name = models.CharField(max_length=255, default="")
    email = models.CharField(max_length=255, default="")
    organization = models.CharField(max_length=255, default="")
    billing_address = models.TextField(default="", blank=True)

    ticket_type = models.CharField(max_length=255)
    dinner_guest = models.CharField(max_length=255, default="", blank=True)
    dinner_guest_qty = models.IntegerField(default=0)

    conference_dinner = models.CharField(max_length=255, default="", blank=True)
    reception_guest = models.CharField(max_length=255, default="", blank=True)
    reception_guest_qty = models.IntegerField(default=0)

    total_amount = models.CharField(max_length=255)
    payment_type = models.CharField(choices=PAYMENT_TYPE, max_length=255)

    products = JSONField(blank=True, null=True)
    qbo_id = models.IntegerField(blank=True, null=True)

    source_url = models.CharField(max_length=255)

    billing_html = HTMLField(default="")
    product_html = models.TextField(default="")

    last_synced = models.DateTimeField(auto_now=True)
    access_key = models.CharField(max_length=32, blank=True)

    is_group = models.BooleanField(default=False)

    def save(self, force_insert=False, force_update=False, using=None):
        if not self.access_key:
            self.access_key = uuid.uuid4().hex

        super(ConferenceRegistration, self).save(
            force_insert=force_insert, force_update=force_update, using=using
        )

    def get_access_key_url(self):
        return reverse(
            "conferences:invoice_preview",
            kwargs={"pk": self.id, "access_key": self.access_key},
        )

    def get_absolute_url(self):
        return "/conferences/#registration-{}".format(self.id)

    def email_invoice(self):
        body = """Thank you for registering for Open Education Global Conference 2018 (24-26 April in Delft, the Netherlands).

Attached is your invoice.

Do not hesitate to contact us at conference@oeglobal.org if you have any questions.
We look forward to welcoming you in the Netherlands!

Open Education Global Conference 2018 Planning Team.
"""

        message = EmailMessage(
            subject="Open Education Global Conference 2018 - Invoice",
            body=body,
            from_email="conference@oeglobal.org",
            to=[self.email],
            # bcc = ['conference@oeglobal.org']
        )

        url = "%s%s" % (settings.INVOICES_PHANTOM_JS_HOST, self.get_access_key_url())
        pdf_file = print_pdf(url)

        message.attach(
            filename="OEGlobal-Invoice-%s.pdf" % self.entry_id,
            content=pdf_file,
            mimetype="application/pdf",
        )
        message.send()


CONFERENCE_REGISTRATION_TYPE = (
    ("normal", "Normal registration"),
    ("presenter", "Presenter registration"),
)


class ConferenceEmailTemplate(models.Model):
    subject = models.CharField(max_length=255)
    body_text = models.TextField()
    body_html = models.TextField()
    email_type = models.CharField(
        choices=CONFERENCE_REGISTRATION_TYPE, default="normal", max_length=20
    )

    def __str__(self) -> str:
        return "{}".format(self.subject)


class ConferenceEmailRegistration(models.Model):
    email = models.CharField(max_length=255)
    email_type = models.CharField(
        choices=CONFERENCE_REGISTRATION_TYPE, default="normal", max_length=20
    )

    def __str__(self) -> str:
        return "{} - {}".format(self.email, self.email_type)


class ConferenceEmailLogs(models.Model):
    action = models.CharField(max_length=255)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return "{}".format(self.action)

members/conferences/forms.py
from django import forms

from conferences.models import ConferenceEmailRegistration


class ConnectForm(forms.Form):
    email = forms.EmailField(required=True)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data["email"]

        if not ConferenceEmailRegistration.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError(
                "Unknown email. Please contact conference@oeglobal.org for assistance."
            )

        return cleaned_data

members/conferences/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.contrib import messages
from django.conf import settings
from django.http import HttpResponse
from django.db.models import Q

from vanilla import TemplateView, FormView
from braces.views import StaffuserRequiredMixin

from rest_framework.views import APIView
from rest_framework.response import Response

from crm.utils import print_pdf
from .forms import ConnectForm

from .models import (
    ConferenceRegistration,
    ConferenceEmailLogs,
    ConferenceEmailRegistration,
    ConferenceEmailTemplate,
)
from .utils import sync_conference


class ConferenceIndex(StaffuserRequiredMixin, TemplateView):
    template_name = "conferences/index.html"

    def post(self, request):
        messages.success(self.request, "Conference registrations synced")
        return redirect("conferences:index")

    def get_context_data(self, *args, **kwargs):
        ctx = super(ConferenceIndex, self).get_context_data(*args, **kwargs)

        q = self.request.GET.get("q")
        queryset = ConferenceRegistration.objects.filter(interface=2)
        if q:
            ctx["q"] = q
            queryset = queryset.filter(
                Q(name__icontains=q)
                | Q(organization__icontains=q)
                | Q(billing_html__icontains=q)
            )
        else:
            queryset = ConferenceRegistration.objects.filter(interface=2)

        ctx["registration_list"] = queryset

        return ctx


class InvoicePDF(StaffuserRequiredMixin, TemplateView):
    def get(self, request, pk=None):
        registration = ConferenceRegistration.objects.get(pk=self.kwargs.get("pk"))

        paid_queryparam = ""
        if request.GET.get("paid"):
            paid_queryparam = "?paid=1"

        url = "{}{}{}".format(
            settings.INVOICES_PHANTOM_JS_HOST,
            registration.get_access_key_url(),
            paid_queryparam,
        )

        pdf_file = print_pdf(url)

        response = HttpResponse(pdf_file, content_type="application/pdf")
        response[
            "Content-Disposition"
        ] = "inline;filename=OEGlobal-Invoice-{}.pdf".format(registration.entry_id)
        return response


class InvoicePreview(TemplateView):
    template_name = "conferences/invoice.html"

    def get_context_data(self, *args, **kwargs):
        ctx = super(InvoicePreview, self).get_context_data(*args, **kwargs)

        registration = ConferenceRegistration.objects.get(
            pk=self.kwargs.get("pk"), access_key=self.kwargs.get("access_key")
        )
        ctx["invoice"] = registration

        if self.request.GET.get("paid"):
            ctx["paid"] = True

        return ctx


class PingInvoices(APIView):
    def get(self, request, format=None):
        sync_conference()

        return Response("OK")


class ConnectEmail(FormView):
    template_name = "conferences/email_form.html"
    form_class = ConnectForm

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        reg = ConferenceEmailRegistration.objects.get(email__iexact=email)
        ConferenceEmailLogs.objects.create(action=str(reg))

        template = ConferenceEmailTemplate.objects.get(email_type=reg.email_type)
        send_mail(
            template.subject,
            template.body_text,
            "conference@oeglobal.org",
            [email],
            html_message=template.body_html,
        )

        return render(
            self.request, "conferences/email_form-done.html", {"email": email}
        )

members/conferences/templates/conferences/email_form-done.html
{% extends "base.html" %}

{% block title %}Request Invitation to OE Global Connect{% endblock %}

{% block contents %}
    <div class="row">
        <div class="large-12 columns">
            <h1>Login E-mail sent</h1>
            <p>We've sent you a link to your email (<strong>{{ email }}</strong>) that will allow you to login into
                Connect. Please check your spam folder, if you don't receive it in a few minutes.</p>
        </div>
    </div>
{% endblock %}

members/conferences/templates/conferences/email_form.html
{% extends "base.html" %}

{% block title %}Request Invitation to OE Global Connect{% endblock %}

{% block contents %}
    <div class="row">
        <div class="small-12 columns">
            <h1>Request Invitation to OE Global Connect</h1>
        </div>

        <form action="" method="POST">{% csrf_token %}
            {{ form.as_p }}

            <input type="submit" class="button" value="Submit"/>
            <input type="hidden" name="next" value="{{ next }}"/>
        </form>

        <p>Once you fill out the form above, you'll receive e-mail with login information to Connect.</p>
        <p>Please contact <a href="mailto:conference@oeglobal.org">conference@oeglobal.org</a> if you have any problems
            or questions regarding your account.</p>
    </div>
{% endblock %}

members/conferences/templates/conferences/index.html
{% extends "base.html" %}

{% block title %}Conference Registrations{% endblock %}

{% block contents %}
    <div class="row">
        <div class="small-12 columns">
            <h1>Conference Registrations - OE Global 2018</h1>
        </div>

        <form method="GET" target=".">
            <div class="small-4 columns">
                <input type="text" name="q" value="" placeholder="Search terms ..">
            </div>
            <input type="submit" name="Search" value="Search" class="button primary small"">
        </form>

        <div class="small-12 columns">
            {% if q %}
                <p>Search results for: <b>{{ q }}</b> (<a href="/conferences/">Clear</a>)</p>
            {% endif %}
        </div>

        <div class="small-12 columns">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Organization</th>
                    <th>Payment Type</th>
                    <th>Registration Date</th>
                    <th colspan="2">Invoice</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for registration in registration_list %}
                    <tr id="registration-{{ registration.id }}">
                        <td>{{ registration.id }}</td>
                        <td>{{ registration.name }}</td>
                        <td>{{ registration.organization }}</td>
                        <td>{{ registration.payment_type }}</td>
                        <td>{{ registration.entry_created|date:"F j, Y" }}</td>
                        <td>
                            <a href="{% url 'conferences:invoice_download' registration.id %}">Download invoice</a>
                            {# <a href="{% url 'conferences:invoice_preview' registration.id registration.access_key %}">Preview</a> #}
                        </td>
                        <td>
                            <a href="{% url 'conferences:invoice_download' registration.id %}?paid=1">Paid invoice</a>
                            {# <a href="{% url 'conferences:invoice_preview' registration.id registration.access_key %}">Preview</a> #}
                        </td>
                        <td>
                            <a href="/admin/conferences/conferenceregistration/{{ registration.id }}/" target="_blank">Edit</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {% comment %}
                <form method="POST" target=".">
                    {% csrf_token %}
                    <input type="submit" name="Sync" value="Sync">
                </form>
            {% endcomment %}
        </div>
    </div>
{% endblock %}

members/conferences/templates/conferences/invoice.html
{% extends "base.html" %}{% load static %}

{% block headrow %}{% endblock %}
{% block breadcrumbs_wrapper %}{% endblock %}
{% block extra_head %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext" rel="stylesheet">

    <style type="text/css">
        .spacer {
            height: 10px;
        }

        .underline {
            text-decoration: underline;
        }

        img {
            width: 250px !important;
        }

        body {
            font-family: 'Open Sans', 'Helvetica', 'Arial', sans-serif !important;
            font-size: 16px;
        }

        @media print {
            a {
                text-decoration: none !important;
                font-weight: normal !important;
            }

            a[href]:after {
                content: "" !important;
            }

            .row-logo {
                text-align: center;
            }

            .logo {
                float: right;
                margin-top: 50px;
            }

            body {
                width: 640px;
            }

            .large-4 {
                position: relative;
                width: 33.33333%;
            }

            .large-6 {
                position: relative;
                width: 50%;
            }

            .column,
            .columns {
                position: relative;
                padding-left: 0.9375em;
                padding-right: 0.9375em;
                float: left;
            }

            table {
                width: 100%;
                border-collapse: collapse;
            }

            table tbody tr td, table tr td {
                line-height: 1.5;

                font-size: 12px !important;
            }

            td, th {
                border: 1px solid black;
            }

            .description {
                width: 70%;
                text-transform: uppercase;
                text-align: center;

                font-size: 12px !important;

            }

            .amount {
                width: 30%;
                text-transform: uppercase;
                text-align: center;

                font-size: 11px !important;

            }
        }

        #paid {
            font-size: 15em;
            top: 40%;
            left: 20%;
            position: absolute;
            color: rgba(108, 108, 108, 0.1) !important;
        }

        .ubuntu10 {
            font-weight: 200 !important;
            font-size: 10px !important;
        }

        .arial10, .arial10 * {
            font-size: 14px !important;
        }

        p {
            font-size: 12px !important;
        }

        p.note, ul.note li {
            font-size: 12px !important;

            color: #900 !important;
        }

        .product_options {
            margin-bottom: 0;
        }

    </style>
{% endblock %}

{% block contents %}
    <div class="row">
        <div class="large-4 columns">
            <img src="https://conference.oeconsortium.org/2018/wp-content/themes/conf2018/images/logo.svg"/>
        </div>

        <div class="large-4 columns" style="float: right">
            <img src="https://www.openeducationweek.org/assets/images/oec-logo.svg" alt="OE Global logo"
                 class="logo"/><br/>
        </div>
    </div>

    <div class="row" style="margin-top: 20px; margin-bottom: 20px;">
        <div class="large-6 columns">
            <p>Invoice No.: OE18-{{ invoice.entry_id|add:"0"|stringformat:"03d" }} <br/>
                {% if invoice.entry_created %}
                    Date: {{ invoice.entry_created|date:"F j, Y" }}
                {% else %}
                    Date: {{ invoice.pub_date|date:"F j, Y" }}
                {% endif %}
            </p>
        </div>
    </div>

    <div class="row">
        <div class="large-4 columns">
            <p><strong>Billing address:</strong><br/>
                <strong>The Open Education Global</strong><br/>
                60 Thoreau St, Suite 238<br/>
                Concord, MA 01742<br/>
                US Tax ID Number: 01-0908761
            </p>
        </div>
        <div class="large-6 columns" style="float: right;">
            <p><strong>Billed to:</strong><br/>
                {{ invoice.name }}<br/>
                <strong>{{ invoice.organization }}</strong><br/>
                <br/>
                {{ invoice.billing_html|safe }}
            </p>
        </div>
    </div>

    <div class="spacer"></div>
    <div class="row">
        <div class="large-10 columns push-1">

            <p>
                Open Education Global Conference 2018 Registration Fee
                <br/>(24-26 April 2018, Delft, the Netherlands)
                <br/><br/>
                Participant: {{ invoice.name }}
            </p>
            <table>
                {{ invoice.product_html|safe }}
            </table>

        </div>
    </div>
    <div class="spacer"></div>
    <div class="row">
        {% if invoice.invoice_type == 'issued' %}
            <div class="large-10 columns push-1">

                <p>Thank you for your support of the OE Global through the prompt payment of this invoice.</p>

                <p class="note">Please note the following: <br/>
                <ul class="note">
                    <li>Payment is due 30 days from invoice date.</li>
                    <li>Payments not received within 3 months of becoming due will result in membership expiration.</li>
                    <li>All Payments should be made in United States Dollars</li>
                    <li>Please remit payment by Check, Wire Transfer, Bank Draft, or PayPal</li>
                </ul>
                </p>
            </div>
        {% else %}
            <br/>
        {% endif %}
        <div class="large-12 columns">
            <p> Please include invoice number or your name as added note (beneficiary reference).
                <br/><br/>
                Please don’t hesitate to contact us at<a href="mailto:conference@oeglobal.org">conference@oeglobal.org</a>
                if you need any further information.
            </p>
            <p>
                Kind regards,<br/>
                <strong>Open Education Global Conference 2018 Planning Team </strong><br/>

            </p>
        </div>

        <div class="large-10 columns push-1">
            <p>We're looking forward to meeting you at the Conference!</p>
        </div>
        {% if paid %}
            <div id="paid">PAID</div>
        {% endif %}
    </div>

    {% if not paid %}
        {% if invoice.invoice_type != 'issued' %}
            <div style="page-break-before:always;"></div>

            <div class="row">
                <div class="large-4 columns">
                    <img src="{% static 'theme/images/logo.png' %}" alt="OE Global logo"/>
                </div>
            </div>
            <div class="spacer"></div>

            <div class="row">
                <div class="large-12 columns">
                    <p><strong>Paying by check:</strong></p>
                    <p>Check should be made payable to Open Education Global. <br/>
                        <span class="underline">Please include invoice number on the check</span>, and mail the check
                        along with this invoice to:
                    </p>
                    <p style="margin-left: 10px;">
                        Open Education Global<br/>
                        60 Thoreau St, Suite 238<br/>
                        Concord, MA 01742<br/>
                        US Tax ID Number: 01-0908761<br/>
                    </p>
                    <p>Please contact us at conference@oeglobal.org to request US $ rate</p>
                </div>
                <div class="large-12 columns">
                    <p><strong>Electronic payment:</strong></p>
                    <p>Bank transfer information can be found below. <span class="underline">Please include invoice number in payment.</span>
                    </p>
                    <p>
                    <table>
                        <tr>
                            <td>Company Name</td>
                            <td>Open Education Global</td>
                        </tr>
                        <tr>
                            <td>Address</td>
                            <td>60 Thoreau St, Suite 238</td>
                        </tr>
                        <tr>
                            <td>City / State / Zip</td>
                            <td>Concord, MA 01742, USA</td>
                        </tr>
                        <tr>
                            <td>IRS Taxpayer ID#</td>
                            <td>01-0908761</td>
                        </tr>
                        <tr>
                            <td>Bank Name</td>
                            <td>TD Bank Harvard Square</td>
                        </tr>
                        <tr>
                            <td style="vertical-align: text-top;">Bank Branch Address</td>
                            <td style="vertical-align: text-top; line-height: 1.6em;">1270 Massachusetts Ave<br/>
                                Cambridge, MA 02138
                            </td>
                        </tr>
                        <tr>
                            <td>Name on Account</td>
                            <td>Open Education Global</td>
                        </tr>
                        <tr>
                            <td>Account Number</td>
                            <td>8247649706</td>
                        </tr>
                        <tr>
                            <td>Account Type</td>
                            <td>Checking</td>
                        </tr>
                        <tr>
                            <td>Bank Transit Routing # (ABA)</td>
                            <td>211370545</td>
                        </tr>
                        <tr>
                            <td>International SWIFT Code</td>
                            <td>NRTHUS33</td>
                        </tr>
                    </table>
                    </p>
                </div>
                {% if invoice.paypal_link %}
                    <div class="large-12 columns">
                        <p><strong>Paypal:</strong></p>
                        <p>Submit payment through PayPal using the following link: <br/>
                            <a href="{{ invoice.paypal_link|safe }}">{{ invoice.paypal_link|safe }}</a><br/><br/>
                            <span class="underline">Please include invoice number as added note.</span>
                        </p>
                    </div>
                {% else %}
                    <div class="large-12 columns">
                        <p><strong>Paypal:</strong></p>
                        <p>Please contact us to get a PayPal payment link.</p>
                    </div>
                {% endif %}
            </div>
        {% endif %}
    {% endif %}

{% endblock %}