members/conferences/urls.py
from django.urls import path

from .views import (
    ConferenceIndex,
    InvoicePDF,
    InvoicePreview,
    PingInvoices,
    ConnectEmail,
)

app_name = "conferences"
urlpatterns = [
    path("", ConferenceIndex.as_view(), name="index"),
    path("invoice/ping/", PingInvoices.as_view(), name="invoice_ping"),
    path("invoice/<int:pk>/", InvoicePDF.as_view(), name="invoice_download"),
    path(
        "invoice/<int:pk>/<str:access_key>/",
        InvoicePreview.as_view(),
        name="invoice_preview",
    ),
    path("connect/", ConnectEmail.as_view(), name="connect_email"),
]

members/crm/urls.py
from django.urls import path

from .views import OrganizationIndex, OrganizationDetailView, OrganizationEdit, \
    ReportedStatisticDetailView, ReportedStatisticEditView, ReportedStatisticAddView, \
    AddressEditView

from vanilla import TemplateView

app_name = 'crm'
urlpatterns = [
    path('member/view/<int:pk>/', OrganizationDetailView.as_view(), name='organization-view'),
    path('member/edit/<int:pk>/', OrganizationEdit.as_view(), name='organization-edit'),
    path('member/address/edit/<int:pk>/', AddressEditView.as_view(), name='address-edit'),
    path('member/statistics/view/<int:pk>/', ReportedStatisticDetailView.as_view(),
        name='reported-statistics-view'),
    path('member/statistics/edit/<int:pk>/', ReportedStatisticEditView.as_view(), name='reported-statistics-edit'),
    path('member/statistics/add/<int:pk>/', ReportedStatisticAddView.as_view(), name='reported-statistics-add'),
    path('', OrganizationIndex.as_view(), name='index'),
]

members/elections/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from .views import (
    CandidateAddView,
    CandidateEditView,
    CandidateView,
    ElectionListView,
    VoteView,
    VoteAddFormView,
    VoteResults,
)
from .api import ElectionCandidatesListAPIView

app_name = "elections"
urlpatterns = [
    path("candidate/nominate/", CandidateAddView.as_view(), name="candidate-add"),
    path(
        "candidate/edit/<str:key>/",
        CandidateEditView.as_view(lookup_field="edit_link_key", lookup_url_kwarg="key"),
        name="candidate-edit",
    ),
    path(
        "candidate/view/<str:key>/",
        CandidateView.as_view(lookup_field="view_link_key", lookup_url_kwarg="key"),
        name="candidate-view",
    ),
    path(
        "candidate/list/<str:key>/",
        ElectionListView.as_view(
            lookup_field="view_nominations_key", lookup_url_kwarg="key"
        ),
        name="candidate-list",
    ),
    path(
        "api/candidate/list/<str:key>/",
        ElectionCandidatesListAPIView.as_view(),
        name="api-candidate-list",
    ),
    path("vote/add/<int:pk>/", VoteAddFormView.as_view(), name="vote-add"),
    path("vote/<int:pk>/", VoteView.as_view(), name="vote-view"),
    path("vote/results/", VoteResults.as_view(), name="vote-results"),
]

members/members/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static

from django.contrib import admin
from django.views.static import serve
from crm.views import IndexView, LoginKeyCheckView

admin.autodiscover()

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("api/v1/", include("crm.urls_api")),
    path("crm/", include("crm.urls")),
    path("staff/", include("crm.urls_staff")),
    path("application/", include("crm.urls_application")),
    path(
        "login/<str:key>/",
        LoginKeyCheckView.as_view(),
        name="login-key-check",
    ),
    path("conferences/", include("conferences.urls")),
    path("elections/", include("elections.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("", IndexView.as_view(), name="crm_index"),
]

if settings.DEBUG:
    urlpatterns += [
        path(
            "media/logos/<path:path>",
            serve,
            {"document_root": settings.MEDIA_ROOT + '/logos/'},
        ),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/crm/models.py
# -*- coding: utf-8 -*-
import os
import uuid
import subprocess
import datetime
import time
import random
import arrow
import sys

from django.db import models, IntegrityError
from django.db.models.signals import post_save
from django.utils.text import slugify
from django.urls import reverse
from django.core.mail import send_mail, EmailMessage
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.conf import settings
from django.dispatch import receiver

from quickbooks import Oauth2SessionManager
from quickbooks import QuickBooks
from quickbooks.exceptions import QuickbooksException
from quickbooks.helpers import qb_date_format
from quickbooks.objects.base import PhoneNumber, EmailAddress
from quickbooks.objects.base import Address as QuickBooksAddress
from quickbooks.objects.customer import Customer
from quickbooks.objects.detailline import SalesItemLine, SalesItemLineDetail
from quickbooks.objects.invoice import Invoice as QuickBooksInvoice
from quickbooks.objects.item import Item
from quickbooks.objects.term import Term

from geopy import geocoders
from geopy.exc import GeocoderTimedOut

from .utils import print_pdf

here = lambda x: os.path.join(os.path.dirname(os.path.abspath(__file__)), x)


class Continent(models.Model):
    name = models.CharField(max_length=192, unique=True, blank=True)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=192, unique=True, blank=True)
    iso_code = models.CharField(max_length=6, unique=True, blank=True)
    developing = models.BooleanField()
    continent = models.ForeignKey(Continent, models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


ORGANIZATION_MEMBERSHIP_TYPE_CHOICES = (
    (5, "Institutional Members"),
    (10, "Institutional Members - MRC"),
    (11, "Institutional Members - DC"),
    (12, "Institutional Members - DC - MRC"),
    (9, "Associate Institutional Members"),
    (17, "Associate Institutional Members - DC"),
    (6, "Organizational Members"),
    (13, "Organizational Members - DC"),
    (18, "Organizational Members - MRC"),
    (7, "Associate Consortium Members"),
    (14, "Associate Consortium Members - DC"),
    (8, "Corporate Members - Basic"),
    (15, "Corporate Members - Premium"),
    (16, "Corporate Members - Sustaining"),
)

ORGANIZATION_TYPE_CHOICES = (
    ("university", "Higher Education Institution"),
    ("npo", "Non-Profit Organization"),
    ("ngo", "Non-Governmental Organization"),
    ("regionalconsortium", "Regional Consortium"),
    ("software", "Software Development"),
    ("commercial", "Commercial Entity"),
)

INSTITUTION_TYPE_CHOICES = (
    ("secondary-ed", "Primary and secondary (K-12)"),
    ("college", "Community, technical, or vocational college"),
    ("higher-ed", "University"),
    ("non-accredited", "Informal non-accredited education"),
    ("lifelong", "Lifelong learning"),
    ("consortium", "Consortia Member"),
    ("consortium-org", "Consortia Organization"),
    ("initiative", "Open initiatives or special project"),
    ("commercial", "Corporate enterprise"),
    ("npo", "Non-profits, NGO’s, IGO"),
    ("cultural", "Cultural organization"),
    ("gov", "Government"),
)

ORGANIZATION_MEMBERSHIP_STATUS = (
    (1, "Applied"),
    (2, "Current"),
    (3, "Grace"),
    (4, "Expired"),
    (5, "Pending"),
    (6, "Cancelled"),
    (7, "Sustaining"),
    # (8,   'Deceased'),
    # (9,   'Testing'),
    # (10,'Committee'),
    # (11,'Committee'),
    # (12,'Suspended'),
    # (13,'New'),
    (99, "Example"),
)

ORGANIZATION_ASSOCIATED_CONSORTIUM = (
    ("CCCOER", "Community College Consortium for Open Educational Resources (CCCOER)"),
    ("CORE", "CORE"),
    ("JOCWC", "OE Japan"),
    ("KOCWC", "Korea OCW Consortium"),
    ("TOCEC", "Taiwan Open Course and Education Consortium"),
    ("Turkish OCWC", "Turkish OpenCourseWare Consortium"),
    ("UNIVERSIA", "UNIVERSIA"),
    ("FOCW", "Open Education France"),
    ("OTHER", "OTHER"),
)

ORGANIZATION_BILLING_TYPE = (
    ("normal", "Normal billing"),
    ("consortia", "Billed via Associate Consortia"),
    ("custom", "Custom Agreement"),
    ("waiver", "Fee waiver"),
)


class ActiveOrganizationManager(models.Manager):
    def get_queryset(self):
        return (
            super(ActiveOrganizationManager, self)
            .get_queryset()
            .filter(membership_status__in=(2, 3, 5, 7, 99))
            .order_by("display_name")
        )


class Organization(models.Model):
    legal_name = models.CharField(max_length=255, blank=True)
    display_name = models.CharField(
        max_length=255, verbose_name="Name of the organization"
    )
    slug = models.CharField(max_length=60, unique=True, default="")
    user = models.ForeignKey(User, models.CASCADE, blank=True, null=True)

    membership_type = models.IntegerField(choices=ORGANIZATION_MEMBERSHIP_TYPE_CHOICES)
    # organization_type = models.CharField(max_length=255, choices=ORGANIZATION_TYPE_CHOICES)
    membership_status = models.IntegerField(choices=ORGANIZATION_MEMBERSHIP_STATUS)
    billing_type = models.CharField(
        max_length=128, choices=ORGANIZATION_BILLING_TYPE, default="normal"
    )
    associate_consortium = models.CharField(
        max_length=255,
        choices=ORGANIZATION_ASSOCIATED_CONSORTIUM,
        blank=True,
        default="",
    )

    qbo_id = models.IntegerField(null=True, blank=True, default=None)

    main_website = models.URLField(max_length=255, blank=True)
    ocw_website = models.URLField(
        max_length=255, blank=True, verbose_name="OER/OCW Website"
    )

    description = models.TextField(blank=True)
    logo_large = models.ImageField(max_length=255, upload_to="logos", blank=True)
    logo_small = models.ImageField(max_length=255, upload_to="logos", blank=True)
    rss_course_feed = models.CharField(max_length=255, blank=True)

    accreditation_body = models.CharField(max_length=255, blank=True, default="")
    support_commitment = models.TextField(blank=True, default="")

    ocw_contact = models.ForeignKey(
        User,
        models.CASCADE,
        null=True,
        verbose_name="Primary contact inside OCW",
        related_name="ocw_contact_user",
        limit_choices_to={"is_staff": True},
    )

    created = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    modified = models.DateTimeField(blank=True, auto_now=True)

    institution_type = models.CharField(
        max_length=25, blank=True, choices=INSTITUTION_TYPE_CHOICES, default=""
    )

    initiative_title1 = models.CharField(
        max_length=255, blank=True, default="", verbose_name="Initiative 1 Title"
    )
    initiative_description1 = models.TextField(
        blank=True,
        default="",
        verbose_name="Initiative 1 Description (100 – 350 characters)",
    )
    initiative_url1 = models.URLField(
        max_length=255, blank=True, default="", verbose_name="Initiative 1 URL"
    )

    initiative_title2 = models.CharField(
        max_length=255, blank=True, default="", verbose_name="Initiative 2 Title"
    )
    initiative_description2 = models.TextField(
        blank=True,
        default="",
        verbose_name="Initiative 2 Description (100 – 350 characters)",
    )
    initiative_url2 = models.URLField(
        max_length=255, blank=True, default="", verbose_name="Initiative 2 URL"
    )

    initiative_title3 = models.CharField(
        max_length=255, blank=True, default="", verbose_name="Initiative 3 Title"
    )
    initiative_description3 = models.TextField(
        blank=True,
        default="",
        verbose_name="Initiative 3 Description (100 – 350 characters)",
    )
    initiative_url3 = models.URLField(
        max_length=255, blank=True, default="", verbose_name="Initiative 3 URL"
    )

    individual_member = models.BooleanField(
        default=False, verbose_name="Individual member?"
    )
    org_affiliation = models.CharField(  # used only for individual members
        max_length=255,
        blank=True,
        default="",
        verbose_name="Organizational Affiliation",
    )

    objects = models.Manager()
    active = ActiveOrganizationManager()

    def __str__(self):
        return self.display_name

    def get_absolute_staff_url(self):
        return reverse("staff:organization-view", kwargs={"pk": self.id})

    def get_absolute_url(self):
        return reverse("crm:organization-view", kwargs={"pk": self.id})

    def get_logo_small_url(self):
        return "https://www.oeconsortium.org/media/%s" % self.logo_small

    def save(self, force_insert=False, force_update=False, using=None):
        if not self.slug:
            slug = slugify(self.display_name)[:30]
            if Organization.objects.filter(slug=slug).exists():
                slug = slug[:29] + "2"
            self.slug = slug

        super(Organization, self).save(
            force_insert=force_insert, force_update=force_update, using=using
        )

        if not self.qbo_id and self.membership_status != 1:
            try:
                qb_client, profile = Profile.get_qb_client()
                self.sync_quickbooks_customer(qb_client)
            except QuickbooksException as e:
                print(
                    "ERROR: unable to sync with QuickBooks: %s (org. ID: %d)"
                    % (e, self.id),
                    file=sys.stderr,
                )

    def get_membership_due_amount(self):
        # Sustaining members
        if self.membership_status in [7] or self.billing_type in [
            "custom",
            "consortia",
            "waiver",
        ]:
            return 0  # manually processed

        if self.associate_consortium == "CCCOER":
            return 650

        try:
            previous_invoice = self.billinglog_set.filter(

members/crm/templates/staff/billinglog_form.html
{% load crispy_forms_tags %}

<div class="large-12 columns">
	<h2>Billing information</h2>

	<table class="billinglog-table">
	<thead>
		<tr>
			<th>Type</th>
			<th>Date</th>
			<th>Who</th>
			<th colspan="2">Actions</th>
			<th>Notes</th>
		</tr>
	</thead>
	<tbody>
	{% for log in object.billinglog_set.all %}
		<tr>
			<td>{{ log.get_log_type_display }}</td>
			<td>{{ log.pub_date|date:"Y-m-d" }}</td>
			<td>{{ log.user }}</td>
			{% if log.log_type == 'create_invoice' or log.log_type == 'create_paid_invoice' %}
                {% if log.qbo_id %}
                    <td colspan="2"><a href="{{ log.get_qbo_url }}" target="_blank">View Invoice in QBO</a></td>
                {% else %}
				    <td><a href="{{ log.invoice.get_pdf_url }}" target="_blank">View Invoice</a></td>
                {% endif %}
			{% elif log.log_type == 'create_payment' %}
                <td colspan="2"><a href="{{ log.get_qbo_url }}" target="_blank">View Payment in QBO</a></td>
            {% else %}
				<td><a href="{% url 'admin:crm_billinglog_change' log.id %}" target="_blank">View log</a></td>
			{% endif %}
			{% if log.log_type == 'create_invoice' or log.log_type == 'create_paid_invoice' %}
				{% if log.invoice %}
                    <td><a href="{% url 'admin:crm_invoice_delete' log.invoice.id %}" target="_blank">Delete</a></td>
                {% endif %}
            {% elif log.log_type == 'create_payment' %}

			{% else %}
				<td><a href="{% url 'admin:crm_billinglog_delete' log.id %}" target="_blank">Delete</a></td>
			{% endif %}
			{% if log.log_type == 'create_note' or log.log_type == 'create_general_note' %}
				<td class="note-col">{{ log.note }}</td>
			{% endif %}
		</tr>
	{% endfor %}
	</tbody>
	</table>

    <p>Billing type: {{ object.get_billing_type_display }} (<a href="{% url 'admin:crm_organization_change' object.id %}" target="_blank">change</a>)</p>

	<div class="small-6 columns">
		<form action="{% url 'staff:billinglog-create' %}" method="POST" class="billing-form" ng-controller="BillingController">
			{% csrf_token %}
			{% crispy form %}
		</form>
	</div>

    <a class="button primary"
            href="https://c1.qbo.intuit.com/app/invoice?nameId={{ object.qbo_id }}" target="_blank">Create new invoice in QBO</a>

</div>

members/crm/templates/staff/billinglog_listing.html
{% extends "staff/organization_base.html" %}

{% block contents %}
    <div class="row">
        <div class="large-12 columns">
            <table>
                <thead>
                <tr>
                    <th>Institution's Name</th>
                    <th>Membership Type</th>
                    <th>Billing Type</th>
                    <th>{{ PREVIOUS_INVOICE_YEAR }} Invoices</th>
                    <th>{{ CURRENT_INVOICE_YEAR }} Invoices</th>
                </tr>
                </thead>
                {% for org in object_list %}
                    <tr>
                        <td><a href="{% url 'staff:organization-view' org.id %}">{{ org.display_name }}</a></td>
                        <td>{{ org.get_membership_status_display }}</td>
                        <td>{{ org.get_billing_type_display }}</td>

                        {% with org.get_last_year_invoice_status as status %}
                            {% if status.create_invoice and status.send_invoice %}
                                <td>created, sent</td>
                            {% elif status.create_invoice %}
                                <td>created</td>
                            {% elif status.send_invoice %}
                                <td>sent</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        {% endwith %}

                        {% with org.get_invoice_status as status %}
                            {% if status.create_invoice and status.send_invoice %}
                                <td>created, sent</td>
                            {% elif status.create_invoice %}
                                <td>created</td>
                            {% elif status.send_invoice %}
                                <td>sent</td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        {% endwith %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

members/crm/templates/staff/index.html
{% extends "base.html" %}

{% block contents %}
    <div class="row">
        <div class="large-6 columns">
            <ul>
                <li><a href="{% url 'staff:organization-list' %}">Organization list</a>
                    <ul>
                        <li><a href="{% url 'staff:organization-list-nocontact' %}">Organizations without valid email
                            contact</a></li>
                        <li><a href="{% url 'staff:organization-list-excel' %}">Excel export</a></li>
                        <li><a href="{% url 'staff:organization-list-cccoer' %}">CCCOER</a></li>
                    </ul>
                </li>
                <li><a href="{% url 'application:application-list' %}">Application list</a></li>
                <li>Invoices: <a href="{% url 'staff:billinglog-username-listing' 'igorlesko' %}">Igor</a>, <a
                        href="{% url 'staff:billinglog-username-listing' 'marcela' %}">Marcela</a></li>
                <li><a href="{% url 'elections:vote-results' %}">Vote results</a></li>
            </ul>
        </div>
        <div class="large-6 columns">
            <ul>
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin GUI</a></li>
                {% endif %}
                <li><a href="{% url 'staff:quickbooks' %}">Quickbooks</a></li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">
            <h3>Conference</h3>
            <ul>
                <li><a href="{% url 'conferences:index' %}">View registrations</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

members/crm/templates/staff/organization_base.html
{% extends "base.html" %}{% load static %}

{% block extra_head %}
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular-resource.min.js"></script>

{% endblock %}

{% block extra_foot %}
	<script src="{% static 'js/staff-script.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
			<li><a href="/">Home</a></li>
			<li><a href="{% url 'staff:organization-list' %}">Organization list</a></li>
{% endblock %}

members/crm/templates/staff/organization_cccoer.html
{% extends "staff/organization_base.html" %}

{% block contents %}
    <div class="row">
        <div class="large-12 columns">
            &nbsp;<a class="button small primary" href="{% url 'staff:organization-list-excel-cccoer' %}">Export to Excel</a>
        </div>

        <div class="large-12 columns">
            <table>
                <thead>
                <tr>
                    <th>Institution's Name</th>
                    <th>Joined</th>
                    <th>Last Paid Invoice</th>
                    <th>State</th>
                    <th>Contact</th>
                </tr>
                </thead>
                {% for org in object_list %}
                    <tr>
                        <td><a href="{% url 'staff:organization-view' org.id %}">{{ org.display_name }}</a></td>
                        <td>{{ org.created|date:"Y-m" }}</td>
                        <td>{{ org.get_last_paid_invoice.pub_date|date:"Y-m" }}</td>
                        <td>{{ org.get_billing_address.state_province }}</td>
                        <td><a href="mailto:{{ org.get_lead_contact.email }}">{{ org.get_lead_contact.first_name }} {{ org.get_lead_contact.last_name }}</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

members/crm/templates/staff/organization_detail.html
{% extends "staff/organization_base.html" %}{% load static %}

{% block extra_head %}
	<link href="{% static 'uni-form/css/uni-form.css' %}" media="screen, projector, print" rel="stylesheet" type="text/css" />
	<link href="{% static 'uni-form/css/default.uni-form.css' %}" media="screen, projector, print" rel="stylesheet" type="text/css" />

	{{ block.super }}
{% endblock %}

{% block title %}{{ org.display_name }}{% endblock %}
{% block breadcrumbs %}
	{{ block.super }}
	<li><a href="#">{{ org.display_name }}</a></li>
{% endblock %}

{% block contents %}
	<div class="row" ng-app="orgApp">
		<div class="large-12 columns">
			<h1 class="display-name">{{ org.display_name }} <a class="edit-link" href="{% url 'admin:crm_organization_change' org.id %}" target="_blank">(Admin Edit)</a></h1>
		</div>
		{% include "_organization_info_full.html" %}
		{% include "staff/billinglog_form.html" %}
	</div>
{% endblock %}

members/crm/templates/staff/organization_list.html
{% extends "staff/organization_base.html" %}

{% block contents %}
<div class="row">
	<div class="large-12 columns">
		<table>
			<thead>
				<tr>
					<th>Institution's Name</th>
					<th>Membership Type</th>
					<th>AC - Member</th>
					<th>Status</th>
					<th>Invalid contacts</th>
                    <th>Geo</th>
				</tr>
			</thead>
			{% for org in object_list %}
				<tr>
					<td><a href="{% url 'staff:organization-view' org.id %}">{{ org.display_name }}</a></td>
					<td>{{ org.get_membership_type_display }}</td>
					<td>{{ org.associate_consortium }}</td>
					<td>{{ org.get_membership_status_display }}</td>
					{% if org.get_bouncing_contacts %}
						<td class="warning">{{ org.get_bouncing_contacts.count }}</td>
                    {% else %}
                        <td></td>
					{% endif %}
                    <td>
                        {% if not org.get_geo.latitude and not org.get_geo.longitude %}
                            X
                        {% endif %}
                    </td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

members/crm/templates/staff/organization_nocontact.html
{% extends "staff/organization_base.html" %}

{% block contents %}
<div class="row">
	<div class="large-12 columns">
		<table>
			<thead>
				<tr>
					<th>Institution's Name</th>
					<th>Membership Type</th>
					<th>AC - Member</th>
					<th>Status</th>
				</tr>
			</thead>
			{% for org in object_list %}
				<tr>
					<td><a href="{% url 'staff:organization-view' org.id %}">{{ org.display_name }}</a></td>
					<td>{{ org.get_membership_type_display }}</td>
					<td>{{ org.associate_consortium }}</td>
					<td>{{ org.get_membership_status_display }}</td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}